### ISSUE TITLE
ledger report with leading filenam

### ISSUE THREAD

**Issue by chrisoswald** [ledger/ledger-mode#275]
Hello I'm try to using ledger with windows (10). It's working well but the ledger report shows always in the first column the complete filename with path. That's completely useless but I cannot find any option to change it. The same  command in the commandline don't showed this, only the normal report with the date first.
Has someone an idea?
Thanks

![ledger-report-with-filenam](https://user-images.githubusercontent.com/10988055/102642839-47914000-412c-11eb-9209-6d93766145d1.JPG)

Windows 10 (binary and chocolatey), Ledger 3.2.1-20200518

**Comment by bcc32** [comment]
ledger-mode adds the filename and line number to each line of `register` reports in order to turn them into links (in the correct behavior, you should be able to press `RET` on a register entry and be taken to the corresponding transaction)---see `ledger-report--cmd-needs-links-p`.

Unfortunately, it looks like the `ledger-report--add-links` functionality expects a Unix-style absolute path (i.e., one beginning with `/`), so it doesn't match the Windows path that ledger outputs.  Probably fixing that regexp will address this bug.

**Comment by chrisoswald** [comment]
Is it possible to fix the regexp by myself?

**Comment by bcc32** [comment]
Sure, can you try evalling (e.g., paste into scratch buffer and `M-x eval-buffer`):

```elisp
(defun ledger-report--add-links ()
  "Replace file and line annotations with buttons."
  (while (re-search-forward "^\\(\\(?:/\\|[a-zA-Z]:[\\/]\\)[^:]+\\)?:\\([0-9]+\\)?:" nil t)
    (let ((file (match-string 1))
          (line (string-to-number (match-string 2))))
      (delete-region (match-beginning 0) (match-end 0))
      (when (and file line)
        (add-text-properties (line-beginning-position) (line-end-position)
                             (list 'ledger-source (cons file line)))
        (make-text-button
         (line-beginning-position) (line-end-position)
         'type 'ledger-report-register-entry
         'help-echo (format "mouse-2, RET: Visit %s:%d" file line))
        ;; Appending the face preserves Ledger's native highlighting
        (font-lock-append-text-property (line-beginning-position) (line-end-position)
                                        'face 'ledger-font-report-clickable-face)
        (end-of-line)))))
```

That should redefine the function to allow Windows-like absolute paths, hopefully (tested not very thoroughly because I don't have a Windows installation of Emacs).

**Comment by chrisoswald** [comment]
That works! 
Thank you very much,
Christian
