### ISSUE TITLE
ledger-schedule-upcoming doesn't use ledger-use-iso-dates

### ISSUE THREAD

**Issue by jmrgithub** [ledger/ledger-mode#36]
When I use scheduling, dates always come out in YYYY/MM/DD format for me, even though I have ledger-use-iso-dates set to t.

**Comment by purcell** [comment]
This is because there's a `ledger-default-date-format` setting _and_ `ledger-use-iso-dates`, but not all the code checks the latter before using the former. I suggest that we should remove `ledger-use-iso-dates` in favour of simply advising people to use set `ledger-default-date-format` to `"%Y-%m-%d"`. `ledger-use-iso-dates` seems to be a bit of a hacky addition.

**Comment by jmrgithub** [comment]
Thank you - setting ledger-default-date-format as you suggested fixed my problem!

**Comment by purcell** [comment]
Okay, I just pushed a bunch of related changes which overhaul how dates are read and formatted. The suggested incantation is now to `(setq ledger-default-date-format ledger-iso-date-format)`, and this should ensure that dates are read and formatted consistently everywhere.

As part of this, I've switched `ledger-read-date` to use `org-read-date` under the hood, but preferring past dates rather than future dates (as would be the default). So "1" would (today) mean "June 1st", "15 Jan 7" would mean 15th Jan 2007 etc. There was some inconsistently-applied code to change the default month/year for date entry, which I've removed because I think the org shorthand and interface is a net win for date entry speed.

Let me know how you get on.
