### ISSUE TITLE
Narrow to cleared/uncleared/pending

### ISSUE THREAD

**Issue by rougier** [ledger/ledger-mode#376]
I would like to filter the main view for showing only uncleared or cleared or pending. Using `ledger-occur`, it is straighforward for cleared (*) and pending (!) but how do I display only uncleared transactions ? I've a hard time finding a proper regex.

**Comment by rougier** [comment]
I found that `(ledger-occur "\[0-9\]\\ \[a-zA-Z\]")` (or `[0-9]\ [a-zA-Z]` in interactive) works. Maybe there's a better solution but it will do.

**Comment by bcc32** [comment]
FWIW, you could also use `(ledger-occur ledger-payee-uncleared-regex)` which might be a bit more robust.  Also, I have the following report defined in my config which I use for a similar purpose:

```
%(binary) -f %(ledger-file) reg --current -U --group-by account '^Assets' '^Equity' '^Liabilities'
```

Since it's a `reg` report, ledger-mode automatically adds links to each xact so you can quickly visit the original definition.
